version: "3.8"

services: 
  redis:
    image: docker.io/bitnami/redis:6.2
    hostname: redis
    environment:
      - ALLOW_EMPTY_PASSWORD=yes
      - REDIS_DISABLE_COMMANDS=FLUSHDB,FLUSHALL
    ports: 
      - '6379:6379'
    volumes: 
      - './data/redis_data:/bitnami/redis/data'
  redis-commander:
    image: rediscommander/redis-commander:latest
    restart: always
    environment:
      - REDIS_HOSTS=local:redis:6379
    ports: 
      - '8081:8081'
    depends_on: 
      - redis
